// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwfzq5rdY46xXWQCoh-9gafdPI3yo-QHw',
    appId: '1:828690466123:web:82a355914f225dc72ad4ce',
    messagingSenderId: '828690466123',
    projectId: 'journeyrental-b554f',
    authDomain: 'journeyrental-b554f.firebaseapp.com',
    storageBucket: 'journeyrental-b554f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5y7GflNpOaGuImKxD3g4K_GEGA47KEBo',
    appId: '1:828690466123:android:8a4070cc1f0b8caf2ad4ce',
    messagingSenderId: '828690466123',
    projectId: 'journeyrental-b554f',
    storageBucket: 'journeyrental-b554f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwv2byTCYdFscWyvuNAESWyoefW3PE68',
    appId: '1:828690466123:ios:a40095a60c06f7b12ad4ce',
    messagingSenderId: '828690466123',
    projectId: 'journeyrental-b554f',
    storageBucket: 'journeyrental-b554f.appspot.com',
    iosBundleId: 'com.example.journeyrental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwv2byTCYdFscWyvuNAESWyoefW3PE68',
    appId: '1:828690466123:ios:e2487a8870d43fb12ad4ce',
    messagingSenderId: '828690466123',
    projectId: 'journeyrental-b554f',
    storageBucket: 'journeyrental-b554f.appspot.com',
    iosBundleId: 'com.example.journeyrental.RunnerTests',
  );
}
